name: codecov

on: [push, pull_request]

jobs:

  codecov:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out source code
      uses: actions/checkout@v1

    - uses: codecov/codecov-action@v2
      with:
        flags: unittests