name: unit test

on:   
  push:
    branches: [ main, fmt_ci]
    paths:
     - mysqlcluster/**/*
     - utils/*
  pull_request:
    branches: [ main, fmt_ci ]
    paths:
     - mysqlcluster/**/*
     - utils/*

jobs:

  unittest:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out source code
      uses: actions/checkout@v1

    - name: test mysqlcluster
      run: go test ./mysqlcluster/ -v -cover

    - name: test utils
      run: go test ./utils/ -v -cover